import { MigrationInterface, QueryRunner } from "typeorm";

export class AddChannels1697921775119 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `INSERT INTO channel1 (name, created_at, updated_at)
             VALUES
                ('ab3army', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('adam1ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('adamtactic', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('aerobomber', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('aeronavtyua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('aerorozvidka215', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('airborne1126', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('arattauda', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('arey_ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('asgard_fpv', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('batalon_shaiha_mansura', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('belwarriors', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('blgr_sqd', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('bohunbrigade', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('bravo_team_chanel', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('brigada92_war', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('brigade128', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('brigade95', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('buar110ombr', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('budem_bambit', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('bulava3mb', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('centuria_plt', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('chervonakalynabrigade', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('dnepro_rub', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('dugout_uncle_zhora', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('duk67ombr', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('edelweiss10tg', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('escadrone', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('extreme_tourism_company', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('fakhivtsi', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('fatumgroup', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('fedorenkoys', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('fifthbrua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('filimonovgonor', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('marvel_company_ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('firstmehbat', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('flyingskull', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('garuda_46', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('gostrikartuzy', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('grifon501', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('horticka_varta', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ii_mechanized_battalion_zsu', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('it_ta_batia_63', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('k_2_54', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('karpatska_sich', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('khartiia', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('khornegroup', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('kolesnyknews', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('komanda_postril_division', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('kraken_kha', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('krula_duyavola', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('lumieregroup', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('mechbrigade', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('molotgryup', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('mosquitos_ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('neboperemogy', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ngu_3027', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ngu_war_for_peace', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('oaembr46', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('oaembr77', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('odshbr46', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('oghb_108', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ogshb8', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ogshb_109', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ombr28', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ombr47', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ombr66', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ombr72', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ompbr56_oficial', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('pegas_1otbr', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('perun_group', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('pidrozdilshadowoficial', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('polk14', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('polskikorpusochotniczy', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('privid_0222', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('rarog_24ombr', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('robert_magyar', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ronins44_65', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('rubpak', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('russvolcorps', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('sarmat21ompb3', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('shaleni_kabany', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('shershen_ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('shershni68', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('sjtf_odes', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('skylordss', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('smertvorogy', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('sons_fatherland', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('sp_khort', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('spartan_ngu', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('staleviy_kordon', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('steelhornets', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('stugnabat1', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('svoboda_army', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('terraops', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('toro_ua', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('ua_marines_36brigade', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('uakryla', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('umftteam', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('volyn100obrtrO', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('wild_hornets', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('wilddivision82', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()'),
                ('wingeds19osb', 'CURRENT_TIMESTAMP()', 'CURRENT_TIMESTAMP()');
            `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DELETE FROM channel1 WHERE name IN
            ('ab3army',
            'adam1ua',
            'adamtactic',
            'aerobomber',
            'aeronavtyua',
            'aerorozvidka215',
            'airborne1126',
            'arattauda',
            'arey_ua',
            'asgard_fpv',
            'batalon_shaiha_mansura',
            'belwarriors',
            'blgr_sqd',
            'bohunbrigade',
            'bravo_team_chanel',
            'brigada92_war',
            'brigade128',
            'brigade95',
            'buar110ombr',
            'budem_bambit',
            'bulava3mb',
            'centuria_plt',
            'chervonakalynabrigade',
            'dnepro_rub',
            'dugout_uncle_zhora',
            'duk67ombr',
            'edelweiss10tg',
            'escadrone',
            'extreme_tourism_company',
            'fakhivtsi',
            'fatumgroup',
            'fedorenkoys',
            'fifthbrua',
            'filimonovgonor',
            'marvel_company_ua',
            'firstmehbat',
            'flyingskull',
            'garuda_46',
            'gostrikartuzy',
            'grifon501',
            'horticka_varta',
            'ii_mechanized_battalion_zsu',
            'it_ta_batia_63',
            'k_2_54',
            'karpatska_sich',
            'khartiia',
            'khornegroup',
            'kolesnyknews',
            'komanda_postril_division',
            'kraken_kha',
            'krula_duyavola',
            'lumieregroup',
            'mechbrigade',
            'molotgryup',
            'mosquitos_ua',
            'neboperemogy',
            'ngu_3027',
            'ngu_war_for_peace',
            'oaembr46',
            'oaembr77',
            'odshbr46',
            'oghb_108',
            'ogshb8',
            'ogshb_109',
            'ombr28',
            'ombr47',
            'ombr66',
            'ombr72',
            'ompbr56_oficial',
            'pegas_1otbr',
            'perun_group',
            'pidrozdilshadowoficial',
            'polk14',
            'polskikorpusochotniczy',
            'privid_0222',
            'rarog_24ombr',
            'robert_magyar',
            'ronins44_65',
            'rubpak',
            'russvolcorps',
            'sarmat21ompb3',
            'shaleni_kabany',
            'shershen_ua',
            'shershni68',
            'sjtf_odes',
            'skylordss',
            'smertvorogy',
            'sons_fatherland',
            'sp_khort',
            'spartan_ngu',
            'staleviy_kordon',
            'steelhornets',
            'stugnabat1',
            'svoboda_army',
            'terraops',
            'toro_ua',
            'ua_marines_36brigade',
            'uakryla',
            'umftteam',
            'volyn100obrtrO',
            'wild_hornets',
            'wilddivision82',
            'wingeds19osb');
        `);
    }
}
